//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hidim.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hidim.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hid.im Port for .NET 2.0/ Winforms (c) 2009 Christoph Stoepel.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidim.NET.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidem-Header ungültig. Datei möglicherweise beschädigt oder falsches Format..
        /// </summary>
        internal static string Err_InvalidHidimHeader {
            get {
                return ResourceManager.GetString("Err_InvalidHidimHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Grafik geladen!.
        /// </summary>
        internal static string Err_NoFile {
            get {
                return ResourceManager.GetString("Err_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidim-Header nicht gefunden! Datei möglicherweise beschädigt oder falsches Format..
        /// </summary>
        internal static string Err_NoHidimHeader {
            get {
                return ResourceManager.GetString("Err_NoHidimHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik darf nicht leer sein..
        /// </summary>
        internal static string Err_NoImage {
            get {
                return ResourceManager.GetString("Err_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_All {
            get {
                return ResourceManager.GetString("FileFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG-Dateien (*.png)|*.png|Alle Dateien (*.*)|*.*&quot;.
        /// </summary>
        internal static string FileFilter_Png {
            get {
                return ResourceManager.GetString("FileFilter_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
    }
}
